### PR TITLE
Update resolver system test when ejecting a theme

### PR DESCRIPTION
**Pull request by gazayas**
This addresses the TODO in the resolver system test.
When we update the test to use the theme name that the user wrote when running `eject` and then point to the local partials that were actually ejected into the main app when searching with `bin/resolve`, we get the correct partials which will make our resolver system tests pass.

After ejecting the theme, the resolver system test related to the TODO looks like this:
```ruby
test "`bin/resolve` can resolve `shared/box`" do
  # TODO Figure out how to make this test pass when we're working on a checked out copy of the theme.
  # TODO Figure out how to make this test pass when using a theme other than Light that overrides the box partial.
  assert `ENABLE_VIEW_ANNOTATION=1 bin/resolve shared/box`.include?("app/views/themes/foo/_box.html.erb")
end
```

Joint PR → [bullet_train-base#55](https://github.com/bullet-train-co/bullet_train-base/pull/55)

### CODE REVIEW

**Comment by andrewculver** [comment]
@gazayas Do you mind rebasing this before I merge?

**Comment by gazayas** [comment]
@andrewculver Okay, this one should be good to go too.

I had to delete the `600` from `text-red-600` in `app/views/themes/light/fields/_field.html.erb` to make sure the alerts were working because I was getting a white background for some reason. Besides that, there shouldn't be any changes.

**Comment by andrewculver** [comment]
@gazayas Is this PR still needed after the other big refactor?

**Comment by gazayas** [comment]
@andrewculver After the big refactor I had to move the two lines into the right file, but now that they're there the resolver system test should work now!

Waiting on https://github.com/bullet-train-co/bullet_train-themes/pull/17 since ejecting themes currently breaks.

**Pull request merged**
