### PR TITLE
Implement logic to let developers release their own themes

### LINKED ISSUE #12: Create theme extractor rake task.
For background, see this thread: https://twitter.com/andrewculver/status/1530571140476727297.

To start working on a theme, people can run `rake bullet_train:themes:light:eject[superdope]`. 

However, once they're happy with their theme, they should be able to extract it into a new Ruby gem and publish that.

To facilitate this, I want to propose a user could run `rake bullet_train:themes:light:release[superdope]`.

When they run this, the script:

- clones https://github.com/bullet-train-co/bullet_train/bullet_train-themes-light.
- prompts them to create a new private or public repository at https://github.com/repositories/new.
- prompts them for the git address of that repository.
- updates `git remote origin` to be the new repository.
- pushes to that repository.
- for the view paths, rename all directory or filename references to "light" to "superdope".
- for each view partial, check whether the file in the local repository is different than the one that was just cloned into the new Ruby gem repository from "light". If it's the same, just delete the file from the new "superdope" theme. It should be inherited from the "light" theme instead.
- if a "superdope" view partial was modified in in the local repository compared to the original "light" view partial, then we should copy it into place in the new clone "superdope" Ruby gem repository.
- copy configuration files and all other files into place in the new Ruby gem repository.
- remove all the light configuration files, etc. from the Ruby gem repository.
- update the `gemspec` to reflect the new Ruby gem name, etc.
- commit the new Ruby gem.
- push it to GitHub.
- remove all the theme files from the local repository.

### PR DESCRIPTION
**Pull request by gazayas**
Closes #12

There's still a decent amount of things to do here, but as of now, running the task will replace the necessary files and rename them accordingly. I'll remove the WIP tag when I finish up.

Next I'll have to actually change the strings inside the files which aren't ejected into the main app. For example:
```ruby
module BulletTrain
  module Themes
    module Light # ← This guy
      # Code here...
    end
  end
end
```

### CODE REVIEW

**Comment by gazayas** [comment]
Changed the original theme name to the developer's new theme name in files specific to the gem like `.gemspec`. Next is pushing the content to GitHub and publishing the gem.

**Comment by gazayas** [comment]
@andrewculver There's just a little bit more to do, but as of now we can do the following:

## Make a new gem
1. Add this branch to the gem file and `bundle install`:
```ruby
gem "bullet_train-themes-light", git: "git@github.com:bullet-train-co/bullet_train-themes-light.git", branch: "features/release-theme-task"
```
2. `rake bullet_train:themes:light:eject[custom_theme]`
3. Make edits to the theme in the main application.
4. `rake bullet_train:themes:light:release[custom_theme]` ← This will push to GitHub

## Use the theme in a fresh Bullet Train app
1. After the gem is published, add the new gem to the Gemfile and `bundle install`.
2. `rake bullet_train:themes:custom_theme:install` 
↑
Currently, we can't actually run this install task because the repository we're cloning from (naturally) doesn't have the task. For now, we have to manually write `custom_theme` in `Procfile.dev`, `app/helpers/application_helper.rb`, and `package.json`.

At this point, you can run `bin/dev` and try the theme.

## Side note
To currently try out the installation task, you can reinstall the light theme by running `rake bullet_train:themes:light:install` after you've ejected a custom theme since the installation task exists on this PR's branch.

## Other things to handle
1. The next step is just making sure our tests work on a fresh, main application. They're currently not passing after including a newly published gem, and it says this specific file isn't in the pipeline (after making `bullet_train-themes-custom`): `application.custom.js`. 
2. We delete all the custom theme files from the main app after moving them to the new gem, so we should add `git add .` and commit.

I want to put out a finished product, but there's a decent amount of code here and I figured it would be better to give partial updates like this instead.

**Comment by gazayas** [comment]
Linking #18 here, since the `application.custom.js` error I mentioned in the last comment is related to it.

**Comment by andrewculver** [comment]
@gazayas This is totally crazy! Thanks so much for this!

**Comment by gazayas** [comment]
@andrewculver I definitely underestimated the scope of the task when I started so it took some time, but I'm glad it got merged!

**Pull request merged**
